---
- hosts: debian
  become: yes
  tasks:
    - name: "sudo apt install java 11"
      apt:
        name: openjdk-11-jdk
        state: latest

    - name: "copy jar"
      copy:
        src: /var/lib/jenkins/workspace/sobolevas/freestyle/target/smart-home-1.0-SNAPSHOT.jar
        dest: tmp/sobolevas/smart-home.jar

    - name: "copy conf file"
      copy:
        src: /var/lib/jenkins/workspace/sobolevas/freestyle/smart-home-1.js
        dest: tmp/sobolevas/smart-home-1.js
